In [1]:
#importing the Libraies
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
# Reading the Dataset
dataset = pd.read_csv('insurance_pre.csv')

In [3]:
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [4]:
dataset=pd.get_dummies(dataset,drop_first=True)

In [5]:
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [6]:
indep=dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']]
dep=dataset['charges']

In [7]:
from sklearn.tree import DecisionTreeRegressor

In [8]:
from sklearn.model_selection import GridSearchCV
#from sklearn.tree import DecisionTreeRegressor
param_grid = {'criterion':['mse','mae','friedman_mse'],
              'max_features': ['auto','sqrt','log2'],
              'splitter':['best','random']} 




grid = GridSearchCV(DecisionTreeRegressor(), param_grid, refit = True, verbose = 3,n_jobs=-1) 
   
# fitting the model for grid search 
grid.fit(indep, dep)

C:\Users\HP\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)
[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.

Fitting 3 folds for each of 18 candidates, totalling 54 fits

[Parallel(n_jobs=-1)]: Done  24 tasks      | elapsed:    7.7s
[Parallel(n_jobs=-1)]: Done  47 out of  54 | elapsed:    8.1s remaining:    1.1s
[Parallel(n_jobs=-1)]: Done  54 out of  54 | elapsed:    8.1s finished

GridSearchCV(cv='warn', error_score='raise-deprecating',
             estimator=DecisionTreeRegressor(criterion='mse', max_depth=None,
                                             max_features=None,
                                             max_leaf_nodes=None,
                                             min_impurity_decrease=0.0,
                                             min_impurity_split=None,
                                             min_samples_leaf=1,
                                             min_samples_split=2,
                                             min_weight_fraction_leaf=0.0,
                                             presort=False, random_state=None,
                                             splitter='best'),
             iid='warn', n_jobs=-1,
             param_grid={'criterion': ['mse', 'mae', 'friedman_mse'],
                         'max_features': ['auto', 'sqrt', 'log2'],
                         'splitter': ['best', 'random']},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=3)

In [9]:
# print best parameter after tuning 
#print(grid.best_params_) 
re=grid.cv_results_

print("The R_score value for best parameter {}:".format(grid.best_params_))

The R_score value for best parameter {'criterion': 'mae', 'max_features': 'sqrt', 'splitter': 'best'}:

In [10]:
table=pd.DataFrame.from_dict(re)

In [11]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_splitter,params,split0_test_score,split1_test_score,split2_test_score,mean_test_score,std_test_score,rank_test_score
0,0.041665,0.026557,0.000000,0.000000e+00,mse,auto,best,"{'criterion': 'mse', 'max_features': 'auto', '...",0.701540,0.670000,0.704686,0.692075,0.015663,6
1,0.011874,0.008584,0.005208,7.365808e-03,mse,auto,random,"{'criterion': 'mse', 'max_features': 'auto', '...",0.678240,0.716101,0.704695,0.699679,0.015859,5
2,0.010416,0.007366,0.000000,0.000000e+00,mse,sqrt,best,"{'criterion': 'mse', 'max_features': 'sqrt', '...",0.614543,0.736239,0.706638,0.685807,0.051820,10
3,0.010416,0.007365,0.015626,1.275941e-02,mse,sqrt,random,"{'criterion': 'mse', 'max_features': 'sqrt', '...",0.679820,0.665288,0.691963,0.679023,0.010905,13
4,0.029627,0.013471,0.007407,5.742748e-03,mse,log2,best,"{'criterion': 'mse', 'max_features': 'log2', '...",0.671774,0.720634,0.680954,0.691121,0.021203,7
5,0.013998,0.011429,0.004665,6.597274e-03,mse,log2,random,"{'criterion': 'mse', 'max_features': 'log2', '...",0.716894,0.629243,0.650747,0.665628,0.037299,15
6,0.110995,0.013898,0.006667,4.714492e-03,mae,auto,best,"{'criterion': 'mae', 'max_features': 'auto', '...",0.688512,0.733535,0.683727,0.701924,0.022437,4
7,0.069991,0.000001,0.009999,7.018853e-07,mae,auto,random,"{'criterion': 'mae', 'max_features': 'auto', '...",0.671200,0.711044,0.689696,0.690647,0.016280,8
8,0.066659,0.009428,0.003333,4.713928e-03,mae,sqrt,best,"{'criterion': 'mae', 'max_features': 'sqrt', '...",0.731038,0.676970,0.716148,0.708052,0.022803,1
9,0.053328,0.004715,0.000000,0.000000e+00,mae,sqrt,random,"{'criterion': 'mae', 'max_features': 'sqrt', '...",0.732418,0.745405,0.637097,0.704973,0.048288,3
10,0.053328,0.012469,0.006665,4.713198e-03,mae,log2,best,"{'criterion': 'mae', 'max_features': 'log2', '...",0.653436,0.679900,0.719032,0.684123,0.026946,11
11,0.043329,0.004714,0.006665,4.712973e-03,mae,log2,random,"{'criterion': 'mae', 'max_features': 'log2', '...",0.662477,0.721084,0.651150,0.678237,0.030648,14
12,0.021602,0.010187,0.011239,1.589498e-02,friedman_mse,auto,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.705379,0.655656,0.698052,0.686362,0.021918,9
13,0.017871,0.010565,0.020176,1.827467e-02,friedman_mse,auto,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.628515,0.684403,0.645514,0.652811,0.023392,16
14,0.009908,0.001746,0.001333,1.884582e-03,friedman_mse,sqrt,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.713953,0.725924,0.681799,0.707225,0.018631,2
15,0.013334,0.004712,0.003332,4.712242e-03,friedman_mse,sqrt,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.537391,0.704258,0.661553,0.634401,0.070777,18
16,0.013331,0.004714,0.003337,4.718986e-03,friedman_mse,log2,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.673349,0.708324,0.657141,0.679605,0.021358,12
17,0.010003,0.000005,0.006664,4.712362e-03,friedman_mse,log2,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.695142,0.688886,0.551229,0.645085,0.066416,17

In [12]:
age_input=float(input("Age:"))
bmi_input=float(input("BMI:"))
children_input=float(input("Children:"))
sex_male_input=int(input("Sex Male 0 or 1:"))
smoker_yes_input=int(input("Smoker Yes 0 or 1:"))

Age:40
BMI:48.10
Children:2
Sex Male 0 or 1:1
Smoker Yes 0 or 1:0

In [13]:
Future_Prediction=grid.predict([[age_input,bmi_input,children_input,sex_male_input,smoker_yes_input]])# change the paramter,play with it.
print("Future_Prediction={}".format(Future_Prediction))

Future_Prediction=[28476.73499]